# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        from_database:
            entity:
                class: acmjBundle\Entity\Visiteur
                property: loginvisiteur

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            logout:
                path:   /logout
                target: /accueil

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: true

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                check_path: acmj_login

    access_control:
        - { path: ^/gestion, roles: ROLE_ADMIN }
        - { path: ^/accueil, roles: [ROLE_USER,ROLE_ADMIN] }

    encoders:
        acmjBundle\Entity\Visiteur:
            algorithm: md5
            encode_as_base64: false
            iterations: 0
