acmj_login:
    path:     /login
    defaults: { _controller: acmjBundle:Security:login }
acmj_accueil_visiteur:
    path:     /accueil
    defaults: { _controller: acmjBundle:Default:index }
acmj_logout:
    path:   /logout

acmj_fichefrais:
    path:   /accueil/ficheFrais/{id}
    defaults: { _controller: acmjBundle:Default:fichefrais }

acmj_consulter_fichefrais:
    path:   /accueil/consulter/{id}
    defaults: { _controller: acmjBundle:Default:consulterFichefrais }

acmj_suppression_fiche:
    path:   /accueil/fichefrais/{idFraisHF}/{idVisiteur}
    defaults: { _controller: acmjBundle:Default:suppressionFraisHF }

acmj_updatefiche:
    path:   /accueil/update/{idHF}/{id}
    defaults: { _controller: acmjBundle:Default:updateHF }

acmj_update_forfait:
    path:   /accueil/updateForfait/{idForfait}/{idVisiteur}
    defaults: { _controller: acmjBundle:Default:updateForfait }


acmj_dql_test:
    path:   /accueil/ficheFraisA
    defaults: { _controller: acmjBundle:Default:existCount }
    










