acmj_login:
    path:     /login
    defaults: { _controller: acmjBundle:Security:login }
acmj_accueil_visiteur:
    path:     /accueil
    defaults: { _controller: acmjBundle:Default:index }
acmj_logout:
    path:   /logout

acmj_fichefrais:
    path:   /accueil/ficheFrais/{id}
    defaults: { _controller: acmjBundle:Default:fichefrais }

acmj_consulter_fichefrais:
    path:   /accueil/consulter/{id}
    defaults: { _controller: acmjBundle:Default:consulterFichefrais }

acmj_suppression_fiche:
    path:   /accueil/suppression/{idFraisHF}
    defaults: { _controller: acmjBundle:Default:suppressionFraisHF }

acmj_test_insert:
    path:   /accueil/test/{id}
    defaults: { _controller: acmjBundle:Default:test }










