<?php
namespace acmjBundle\Repository;

/**
 * ArtisanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichefraisRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLesMois() {

    $query = $this->createQueryBuilder('m')
    ->select("m.mois")
    ->getQuery()
    ->getResult();
    }


}