<?php
namespace acmjBundle\Repository;

/**
 * ArtisanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichefraisRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLesMois($idVisiteur) {

        $query = $this->createQueryBuilder('m')
        ->select("m.mois")
        ->where('m.idDeclarer = :idVisiteur')
        ->setParameter('idVisiteur',$idVisiteur)
        ->getQuery()
        ->getResult();
    }

    public function getInfos($mois) {

        $query = $this->createQueryBuilder('m')
                        ->select('m')
                        ->where ('m.mois = :mois')
                        ->setParameter('mois',$mois)
                        ->getQuery();
                       

    }

    public function findByIdVisiteurAndMois($id,$mois) {

        $parameters = array (
            'idVisiteur' =>$id,
            'mois'=>$mois
        );

        $query = $this->createQueryBuilder('f')
                        ->where('f.idvisiteur = :idVisiteur')
                        ->andWhere('f.mois = :mois')
                        ->setParameters($parameters)
                        ->getQuery()
                        ->getResult();
                         return $query;
                    
                        
                    
        }




}