<?php
namespace acmjBundle\Repository;

use acBundle\Entity\Artisan;
use acBundle\Entity\CorpsMetierRecherche;

/**
 * ArtisanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraisForfaitRepository extends \Doctrine\ORM\EntityRepository
{



}