<?php
namespace acmjBundle\Repository;

/**
 * ArtisanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraisforfaitRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLesFraisForfaits() {
        

            $query = $this->createQueryBuilder('m')
            ->select("m.libelle")
            ->getQuery()
            ->getResult();
            }
    



}