<?php
namespace acmjBundle\Repository;


/**
 * ArtisanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignefraisforfaitRepository extends \Doctrine\ORM\EntityRepository
{
  
    public function findByIdVisiteurAndDate($id,$date) {
        
        $parameters = array (
            'idVisiteur' =>$id,
            'dateModif'=>$date
        );

        $query = $this->createQueryBuilder('f')
        ->select('f')
        ->Where('f.idvisiteur = :idVisiteur')
        ->andWhere('f.datemodification = :dateModif')
        ->setParameters($parameters)
        ->getQuery()
        ->getResult();
         return $query;
    
    }

    public function findByDateAndIdVisiteur($date,$id) {
        $parameters = array (
            'idVisiteur' =>$id,
            'dateModif'=>'%'.$date.'%'
        );

        $query = $this->createQueryBuilder('f')
        ->select('f')
        ->Where('f.idvisiteur = :idVisiteur')
        ->andWhere('f.datemodification LIKE :dateModif')
        ->setParameters($parameters)
        ->getQuery()
        ->getResult();
         return $query;
    

    }

    





}