<?php
namespace acmjBundle\Repository;


/**
 * ArtisanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignefraisforfaitRepository extends \Doctrine\ORM\EntityRepository
{



}