<?php
namespace acmjBundle\Repository;


/**
 * ArtisanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignefraishorsforfaitRepository extends \Doctrine\ORM\EntityRepository
{


    public function getLesLignesHFByIdVisiteur($id) {
        $query = $this->createQueryBuilder('f')
        ->select('f')
        ->Where('f.idVisiteur = :id')
        ->setParameter('id',$id)
        ->getQuery()
        ->getResult();
         return $query;

    }



}