<?php
namespace acmjBundle\Repository;

/**
 * ArtisanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLesVisiteurs() {

    $query = $this->createQueryBuilder('v')
    ->select("v.nomvisiteur")
    ->getQuery()
    ->getResult();
    }


}